network/wifimanager: fix assert issue in wifi stress test
Samsung/TizenRT pull request #4805
Opened 2021-02-18 09:03 UTC by gexuyan

Increase the priority of wifi msg handler thread from 100 to 101 to avoid the assert issue in wifi stress test.
Please note that this is a workaround for the assert issue in wifi stress test.

2021-02-18 09:04 UTC, tizen-build commented
Target : [2af21c1bbe53b32c08479cabf7806e0b86cb45ec] - Code Rule Check OK.

2021-02-18 09:58 UTC, Taejun-Kwon commented
TizenRT follows round robin scheduling, so I think if there are many threads in product level, assert will occur again.
This is not good solution, please consider it more and more.

2021-02-18 09:59 UTC, Taejun-Kwon requested changes
please see my comment

2021-02-22 00:53 UTC, davidfather commented
> TizenRT follows round robin scheduling, so I think if there are many threads in product level, assert will occur again.
> This is not good solution, please consider it more and more.

@pillip8282 I also agree with @Taejun-Kwon. This code is for all Wi-Fi chipsets, not for only RTK.

2021-02-22 02:29 UTC, davidfather commented on framework/src/wifi_manager/wifi_manager_msghandler.c
> +	int tid = task_create("wifi msg handler", 101, 4096, (main_t)_process_msg, NULL);
This temporary fix should be avoided because wifi_manager is for all Wi-Fi chipsets, not for only RTK.

2021-02-23 07:34 UTC, gexuyan commented
will raise another PR for this issue~

2021-02-23 07:34 UTC, closed without merging