os/board/rtl8721csm: add wpa tkip aes mixed mode in wifi
Samsung/TizenRT pull request #4881
Opened 2021-03-30 08:29 UTC by gexuyan

Add the wpa tkip aes mixed security mode in wifi scan result

2021-03-30 08:31 UTC, tizen-build commented
Target : [f220624830ff73a9733203f78cef7b41f21b575d] - Code Rule Check OK.

2021-03-31 00:56 UTC, pillip8282 requested changes

2021-03-31 00:56 UTC, pillip8282 commented on os/board/rtl8721csm/src/component/common/api/wifi/rtw_wpa_supplicant/wpa_supplicant/wifi_wps_config.c
> +			printf("\r\nsecurity_type = RTW_SECURITY_WPA_MIXED_PSK\n");
printf is not allowed in kernel space. using vdvdbg for information or vddbg for error

2021-03-31 00:56 UTC, pillip8282 commented on os/board/rtl8721csm/src/component/common/api/wifi_interactive_mode.c
> +	RTW_API_INFO("%s\t\t ", (record->security == RTW_SECURITY_OPEN) ? "Open" : (record->security == RTW_SECURITY_WEP_PSK) ? "WEP" : (record->security == RTW_SECURITY_WPA_TKIP_PSK) ? "WPA TKIP" : (record
the line length is too long. please divide it.

2021-03-31 00:56 UTC, pillip8282 commented on os/board/rtl8721csm/src/component/common/api/wifi_interactive_mode.c
> +			RTW_API_INFO("Security : %s\r\n", (sec == RTW_SECURITY_OPEN) ? "Open" : (sec == RTW_SECURITY_WEP_PSK) ? "WEP" : (sec == RTW_SECURITY_WPA_TKIP_PSK) ? "WPA TKIP" : (sec == RTW_SECURITY_WPA_AES_PSK)
the line length is too long. please divide it.

2021-03-31 04:03 UTC, vibhor-m commented
reference for my id

2021-03-31 12:29 UTC, gexuyan commented
will raise a new pr for this issue.

2021-03-31 12:29 UTC, closed without merging