external/dhcpd_lwip: Fix pthread_create return check in dhcps
Samsung/TizenRT pull request #5001
Opened 2021-06-22 10:08 UTC by j11591

Fix pthread_create return check in dhcps and add detach

2021-06-22 10:09 UTC, tizen-build commented
Target : [ce9189c6c56b30fd006b17d19bbe529c31b340f2] - Code Rule Check OK.

2021-06-22 22:20 UTC, jeongchanKim approved these changes
LGTM

2021-06-23 00:56 UTC, sunghan-chang approved these changes

2021-06-23 13:22 UTC, thapav approved these changes
LGTM

2021-06-24 00:42 UTC, pillip8282 requested changes

2021-06-24 00:42 UTC, pillip8282 commented on external/dhcpd/dhcpd_lwip.c
> +	pthread_detach(g_dhcpd_tid);
You don't need to call pthread_detach here. because pthread_join is called in dhcps_stop().

2021-06-24 02:38 UTC, jeongchanKim approved these changes
LGTM

2021-06-24 02:39 UTC, tizen-build commented
Target : [a163ca9c551ee6685fc7272e1cdeb493d0fe6dc6] - Code Rule Check OK.

2021-06-24 02:48 UTC, pillip8282 approved these changes
Lgtm

2021-06-24 02:48 UTC, merged