rtl8721csm/Make.defs: Fix cxx excteptions flag issue
Samsung/TizenRT pull request #5830
Opened 2023-05-23 09:04 UTC by kishore-sn

The -fexceptions compiler flag must be added only if CONFIG_LIBCXX_EXCEPTION is enabled.

2023-05-23 09:06 UTC, tizen-build commented
Target : [434c7d5dd1e9bb918e205b9f80d11c72eb723fe9] - Code Rule Check OK.

2023-05-23 09:06 UTC, r-prabu requested changes
Looks good.

2023-05-23 09:09 UTC, Tirtha-Samsung submitted a review, later dismissed

2023-05-23 09:09 UTC, Tirtha-Samsung commented on build/configs/rtl8721csm/Make.defs
It looks good to me. Approved~

2023-05-24 10:36 UTC, sunghan-chang commented on build/configs/rtl8721csm/Make.defs
> +ARCHCXXFLAGS = -fno-builtin -mcpu=cortex-m33 -mfpu=fpv5-sp-d16
@kishore-sn Could you check @thapav 's comment?

2023-05-25 07:11 UTC, kishore-sn commented on build/configs/rtl8721csm/Make.defs
> +ARCHCXXFLAGS = -fno-builtin -mcpu=cortex-m33 -mfpu=fpv5-sp-d16
Done thanks.

2023-05-25 07:12 UTC, tizen-build commented
Target : [c5be34009dd423339cb042c977b6b13b53a19dfa] - Code Rule Check OK.

2023-05-25 07:14 UTC, sunghan-chang commented
@kishore-sn Sorry for late comment. You modified two Make.defs. Could you write two location in the title?
```
configs/rtl8721csm, rtl8720e/Make.defs: fix ....

...
```

2023-05-26 03:30 UTC, sunghan-chang approved these changes

2023-05-26 04:02 UTC, jylee9613 approved these changes
LGTM

2023-05-26 05:01 UTC, ewoodev approved these changes
Looks Good to me~

2023-05-26 05:17 UTC, merged