os/Makefile.unix: Changes done to build rtl8730e
Samsung/TizenRT pull request #5850
Opened 2023-06-15 04:41 UTC by Tirtha-Samsung

In rtl8730e and armv7-a architecture, we use CONFIG_FLASH_START instead of CONFIG_FLASH_START_ADDR

2023-06-15 04:55 UTC, sunghan-chang requested changes
Sorry but I don't agree this change. I think we should use CONFIG_FLASH_START_ADDR instead of CONFIG_FLASH_START. There is no reason to use it for only armv7-a.

2023-06-15 04:56 UTC, sunghan-chang commented
@Tirtha-Samsung Please let me know reason of `In rtl8730e and armv7-a architecture, we use CONFIG_FLASH_START instead of CONFIG_FLASH_START_ADDR`.

2023-06-15 06:02 UTC, ewoodev commented on os/Makefile.unix
> +KERNEL_START=$(CONFIG_FLASH_START)
Why we should use two config `CONFIG_FLASH_START` and `CONFIG_FLASH_START_ADDR`?
Is the address value of the two confg different?

If the two address values are the same, I think we can do as below.
```
#define CONFIG_FLASH_START CONFIG_FLASH_START_ADDR
```
or change to use CONFIG_FLASH_START_ADDR in armv7-a

2023-06-16 02:48 UTC, tizen-build commented
Target : [abb33bae4b3d13e1e2883fafa4a19ff1eb6818f7] - Code Rule Check OK.

2023-06-16 02:54 UTC, tizen-build commented
Target : [a778f185ae0c89a76391e0f94f706b40b6330b5e] - Code Rule Check OK.

2023-06-16 03:57 UTC, sunghan-chang approved these changes

2023-06-16 03:59 UTC, sunghan-chang commented
1. `arch/arm/src/armv7-a, arch/arm/src/amebasmart: Use CONFIG_FLASH_START_ADDR as per TizenRT`
is too long. How about below?
`arch/armv7-a, amebasmart: user CONFIG_...._ADDR`
2. There is no commit description. This is not allowed. Please write add some description.

2023-06-16 05:48 UTC, tizen-build commented
Target : [b81cc9047979f10d6a83857ec7f3df2ab74f9355] - Code Rule Check OK.

2023-06-16 06:22 UTC, ewoodev approved these changes
LGTM~

2023-06-16 08:19 UTC, sunghan-chang approved these changes

2023-06-16 08:19 UTC, merged